// GENERATED BY gg_version WriteVersionFile - DO NOT EDIT.
// Kept in sync by test/supply_chain_app_version.test.ts.

/** The version of the `@tssuite/supply-chain-app` package. */
export const supplyChainAppVersion = '0.0.3';
